### ISSUE TITLE
Naming of files

### ISSUE THREAD

**Issue by diegantobass** [regardscitoyens/professions-foi-candidats#1]
Concatenating variables with the dash char '-' when naming the output files clashes with composite family names of candidates like in the following file name : LG17-1-1-BLATRIX-CONTAT-2-tour1-profession_foi where BLATRIX-CONTAT being the family name, you can't just naively split back your file name on dashes.

SHAME ON YOU ROUX

**Comment by diegantobass** [comment]
My bad, this looks like a one shot thing on the example I gave.

**Comment by boogheta** [comment]
ahahaha all right, will check this in a bit :p

**Comment by diegantobass** [comment]
Most composite family names are concatenated with low_dashes.

**Comment by diegantobass** [comment]
Okay back in business it's NOT a one shot thing : LG17-1-3-SACCHI-HASSANEIN-5-tour1-profession_foi

**Comment by diegantobass** [comment]
This means neither low_dashes nor dash- will work. I'm working on a dirty fix in the renaming I'm working on. Will pull request.

**Comment by diegantobass** [comment]
Fuck this shit. Manual work on those two, sorry : 
LG17-33-3-REY--CAPDEPON-22-tour1-profession_foi.pdf
LG17-972-1-MARTHE-DITE-SURELLY-15-tour1-profession_foi.pdf

**Comment by boogheta** [comment]
Do not use split to parse the filenames, use rather a regexp:
`r"(.*)-(\d)-(\d)-(.*)-(\d+)-tour(\d)-(.*)"` => (election, dept, circo, nom, ordre, tour, typedoc)

**Comment by diegantobass** [comment]
For the record : `r"(.*)-(\d+|\d[AB])-(\d+)-(.*)-(\d+)-tour(\d)-(.*)"`

**Comment by boogheta** [comment]
arf yes Corsica :)

**Comment by diegantobass** [comment]
> Corsica has put a bomb in your repo 💣
